### ISSUE TITLE
Error on Other Functionlity  Showing :- "we are unable to access the file at this location"

### ISSUE THREAD

**Issue by Ravipatel401** [Swati4star/Images-to-PDF#1003]
Also Upgraded from current commit.

I have checked and test the recent commit, Creating a PDF file is working perfectly but facing an issue in Add Password, Merge PDF, Add Text, and others, Like showing "we are unable to access the file at this location" after selecting PDF file.

 compileSdkVersion 30
 buildToolsVersion '30.0.3'
 targetSdkVersion 30

**Comment by santutunga** [comment]
Same issue. i'm using it android 10. not working

**Comment by codegsaini** [comment]
I'm unable to reproduce the issue!!!
## What I've tried
- Add password ( no issue )
- Merge PDF ( no issue )

## Tested on
Android studio Emulator Pixel 2 API 30

### Provide more information or step to reproduce the issue, OR Consider sharing specific detail of your testing environment.

## Side Note ~
Similar warning ( "We were unable to access PDF. File may be encrypted or in internal storage." ) is generated when you try to merge password protected pdf files.

**Comment by Ravipatel401** [comment]
@codegsaini 

I have checked password protection, but still showing same issue. (No protected or no encryption)
Using Android 11 
Oneplus nord
Android Studio 4.1.3
Tried  building on both Version on Android 10(29) and 11(30)

(https://user-images.githubusercontent.com/3479149/117924936-2962f100-b314-11eb-9296-8063cd4f2a8a.jpeg)
(https://user-images.githubusercontent.com/3479149/117924938-29fb8780-b314-11eb-921d-47617acc522a.jpeg)

**Comment by codegsaini** [comment]
Thanks for more information, I'm working on it...

**Comment by codegsaini** [comment]
@Ravipatel401 After several try I'm still unable to reproduce this issue. It'll be great if I get to know exactly what's going wrong at your side.
## Do a task
In your local machine add a new line  `Log.d("MergePDFFragment", "Localized message: " + e.getLocalizedMessage() + "\nException: " + e.getMessage() + "\nCause:" + e.getCause());`  after - 
https://github.com/Swati4star/Images-to-PDF/blob/8f6e855e0a339889ec0d6f4f8fab3633cd93bd12/app/src/main/java/swati4star/createpdf/util/MergePdf.java#L84

and then try to merge pdf. If there will be any exception you got that exception in your log. If it happen, share the Log message.

**SideNote ~ Don't share entire log, only share the log message displayed after searching 'MergePDFFragment' in the LogCat searchbox**

**Comment by Ravipatel401** [comment]
@codegsaini 
 Found something like this.

```
 W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/PDF Converter/gch.pdf: open failed: EPERM (Operation not permitted)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
 W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
W/System.err:     at com.advanced.pdfconverter.util.MergePdf.doInBackground(MergePdf.java:62)
 W/System.err:     at com.advanced.pdfconverter.util.MergePdf.doInBackground(MergePdf.java:17)
 W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
/System.err: Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
 W/System.err:     at libcore.io.Linux.open(Native Method)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7865)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err: 	... 10 more
D/MergePDFFragment: Localized message: /storage/emulated/0/Documents/PDF Converter/gch.pdf: open failed: EPERM (Operation not permitted)
    Exception: /storage/emulated/0/Documents/PDF Converter/gch.pdf: open failed: EPERM (Operation not permitted)
```

**Comment by codegsaini** [comment]
Thanks for sharing, I'm looking into it...

**Comment by codegsaini** [comment]
The message 'Operation not permitted' took my concern toward read storage permission related issue. So I tried testing with every scenario of permission allowed or denied but **Still everything went fine as expected**. I'm still unable to reproduce the issue.

I need more info related to the issue.
## Help me understand the issue
- Please share a gif showing the error appearance

**Comment by Ravipatel401** [comment]
Thanks, @codegsaini for making everything proper, I really appreciate your efforts, Please have look at here attach videos. 


https://user-images.githubusercontent.com/3479149/118236220-6f09f000-b4b3-11eb-9662-eb0466c9645b.mp4
https://user-images.githubusercontent.com/3479149/118236227-70d3b380-b4b3-11eb-8ce0-bde483e69892.mp4

**Comment by codegsaini** [comment]
@Ravipatel401 Your welcome mate :) and thanks for your cooperation. I'm looking into it...

**Comment by codegsaini** [comment]
Work is in progress...

**Comment by codegsaini** [comment]
Done!
PR in the morning will have the solution.

**Comment by Ravipatel401** [comment]
@codegsaini Thank you, I will check and let know.

**Comment by atinagrawal** [comment]
@codegsaini I tried your solution. It now gives a popup to select the folder to save files but the original issue is still there. Can't save any PDFs (Error on creating application folder.) I tried granting permission to the app after creating a new folder (from the popup from your solution)

Please help.

**Comment by codegsaini** [comment]
@atinagrawal I am extremely sorry dear, but due to exams I am unable to work on it right now. Once exams are over I will start working on it in no time. Sorry for now. I hope you will understand.

**Comment by atinagrawal** [comment]
Sure @codegsaini, will be waiting for a solution.
All the best for your exams.

**Comment by atinagrawal** [comment]
> @Ravipatel401 After several try I'm still unable to reproduce this issue. It'll be great if I get to know exactly what's going wrong at your side.
> 
> ## Do a task
> In your local machine add a new line `Log.d("MergePDF", "Localized message: " + e.getLocalizedMessage() + "\nException: " + e.getMessage() + "\nCause:" + e.getCause());` after -
> https://github.com/Swati4star/Images-to-PDF/blob/8f6e855e0a339889ec0d6f4f8fab3633cd93bd12/app/src/main/java/swati4star/createpdf/util/MergePdf.java#L84
> 
> and then try to merge pdf. If there will be any exception you got that exception in your log. If it happen, share the Log message.
> 
> **SideNote ~ Don't share entire log, only share the log message displayed after searching 'MergePDF' in the LogCat searchbox**

This is the log:


D/MergePDF: Localized message: /storage/emulated/0/Download/PDF Converter/dy.pdf: open failed: EACCES (Permission denied)0

**Comment by codegsaini** [comment]
> > @Ravipatel401 After several try I'm still unable to reproduce this issue. It'll be great if I get to know exactly what's going wrong at your side.
> > ## Do a task
> > In your local machine add a new line `Log.d("MergePDF", "Localized message: " + e.getLocalizedMessage() + "\nException: " + e.getMessage() + "\nCause:" + e.getCause());` after -
> > https://github.com/Swati4star/Images-to-PDF/blob/8f6e855e0a339889ec0d6f4f8fab3633cd93bd12/app/src/main/java/swati4star/createpdf/util/MergePdf.java#L84
> > 
> > and then try to merge pdf. If there will be any exception you got that exception in your log. If it happen, share the Log message.
> > **SideNote ~ Don't share entire log, only share the log message displayed after searching 'MergePDF' in the LogCat searchbox**
> 
> This is the log on an Android 10 device:
> 
> **D/MergePDF: Localized message: /storage/emulated/0/Download/PDF Converter/dy.pdf: open failed: EACCES (Permission denied)**
> 
> Everything works fine on Android 11 though.

@atinagrawal Thanks for this information, it will really help in debugging.

**Comment by codegsaini** [comment]
> > @Ravipatel401 After several try I'm still unable to reproduce this issue. It'll be great if I get to know exactly what's going wrong at your side.
> > ## Do a task
> > In your local machine add a new line `Log.d("MergePDF", "Localized message: " + e.getLocalizedMessage() + "\nException: " + e.getMessage() + "\nCause:" + e.getCause());` after -
> > https://github.com/Swati4star/Images-to-PDF/blob/8f6e855e0a339889ec0d6f4f8fab3633cd93bd12/app/src/main/java/swati4star/createpdf/util/MergePdf.java#L84
> > 
> > and then try to merge pdf. If there will be any exception you got that exception in your log. If it happen, share the Log message.
> > **SideNote ~ Don't share entire log, only share the log message displayed after searching 'MergePDF' in the LogCat searchbox**
> 
> This is the log on an Android 10 device:
> 
> **D/MergePDF: Localized message: /storage/emulated/0/Download/PDF Converter/dy.pdf: open failed: EACCES (Permission denied)**
> 
> Everything works fine on Android 11 though.

Well, please consider this [stackoverflow answer](https://stackoverflow.com/a/24842735). And let me know if it solve your issue or not.
